# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SportEasyTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Alamofire'

  # Pods for SportEasyTest

  target 'SportEasyTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SportEasyTestUITests' do
    # Pods for testing
  end

end
